# Generated by Django 2.2 on 2020-04-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Nome_de_Bixo', models.CharField(max_length=30)),
                ('Idade', models.IntegerField()),
                ('Ape', models.IntegerField()),
            ],
        ),
    ]
